on:
  push:
#  pull_request: # in pull_request, github action is in a detached HEAD
permissions:
  contents: write
#env:
#  GITHUB_CONTEX: ${{ toJson(github) }}
jobs:
  egg:
    runs-on: ubuntu-latest #public
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - run: sudo apt update && sudo apt install -y m4
    - name: libyaml.egg
      run: |
        cat libyaml.egg.m4 | ./2src/m42egg.sh | tee libyaml.egg
    - name: diff and push
      run: |
        git config user.name  ${{ github.event.repository.owner.name  }}
        git config user.email ${{ github.event.repository.owner.email }}
        git add libyaml.egg
        git diff-index --quiet HEAD || git commit -m '[auto][from github action][include/foreign.scm]'
        git push
