on:
  pull_request:
permissions:
  contents: write
#env:
#  GITHUB_CONTEX: ${{ toJson(github) }}
jobs:
  files:
    runs-on: ubuntu-latest #public
    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.head_ref }} # in pull_request, github action is in a detached HEAD, here checkout the real branch
        submodules: recursive
    - run: sudo apt update && sudo apt install -y clang libclang-dev autoconf m4
    #- run: find /usr/lib/llvm-* -type d -name clang-c
    #- run: find /usr/lib/llvm-* -name libclang.so
    - name: foreign.scm
      run: |
        find /usr/lib/llvm-* -type d -name clang-c -exec ln -sfT {}/.. ./usr \;
        find /usr/lib/llvm-* -name libclang.so -exec ln -sf {} ./lib/. \;
        clang -o foreign -I./usr/. -L./lib/. -lclang 2src/foreign.c
        ./foreign 2src/yaml.h 1>include/foreign.scm
    - name: config.h
      run: ./bootstrap && ./configure
      working-directory: ./src/libyaml
    - run: mv ./src/libyaml/include/config.h ./include/.
    - name: libyaml.egg
      run: |
        cat libyaml.egg.m4 | ./2src/m42egg.sh | tee libyaml.egg
    - name: diff and push
      run: |
        git config user.name ${{ github.actor }}
        git add include/foreign.scm
        git add include/config.h
        git add libyaml.egg
        git diff-index --quiet HEAD || git commit -m '[auto][from github action][include/foreign.scm]'
        git push
