on:
  push:
    branches:
    - main
  pull_request:
permissions:
  contents: write
env:
  GITHUB_CONTEX: ${{ toJson(github) }}
jobs:
  foreign:
    runs-on: ubuntu-latest #public
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - run: mkdir -p include/.
    - run: sudo apt update && sudo apt install -y clang libclang-dev
    #- run: find /usr/lib/llvm-* -type d -name clang-c
    #- run: find /usr/lib/llvm-* -name libclang.so
    - name: foreign.scm
      run: |
        find /usr/lib/llvm-* -type d -name clang-c -exec ln -sfT {}/.. ./usr \;
        find /usr/lib/llvm-* -name libclang.so -exec ln -sf {} ./lib/. \;
        clang -o foreign -I./usr/. -L./lib/. -lclang 2src/foreign.c
        ./foreign src/libyaml/include/yaml.h 1>include/foreign.scm
    - name: diff and push
      run: |
        git config user.name  ${{ github.event.repository.owner.name  }}
        git config user.email ${{ github.event.repository.owner.email }}
        git add include/foreign.scm
        git diff-index --quiet HEAD || git commit -m '[auto][from github action][foreign.scm]'
        git push
