on:
  pull_request:
permissions:
  contents: write
#env:
#  env: env
#  GITHUB_CONTEX: ${{ toJson(github) }}
jobs:
  lincese:
    runs-on: ubuntu-latest #public
    steps:
    - uses: actions/checkout@main
    - run: m4 -P -Dm4_year="$(date +%Y)" -Dm4_email="${{ github.event.repository.owner.email }}" -Dm4_name="${{ github.event.repository.owner.login }}" <.LICENSE.m4 >LICENSE
    - name: license
      run: |
        git config user.name ${{ github.event.pull_request.base.repo.owner.login }}
        git add LICENSE
        git diff-index --quiet HEAD || git commit -m '[auto][from github action][lincese]'
        git push
